export const TOP_SALES_REQUEST = 'TOP_SALES_REQUEST';
export const TOP_SALES_FAILURE = 'TOP_SALES_FAILURE';
export const TOP_SALES_SUCCESS = 'TOP_SALES_SUCCESS';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';

export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS';

export const MORE_REQUEST = 'CATALOG_REQUEST';
export const MORE_FAILURE = 'MORE_FAILURE';
export const MORE_SUCCESS = 'MORE_SUCCESS';