export const TOP_SALES_REQUEST = 'TOP_SALES_REQUEST';
export const TOP_SALES_FAILURE = 'TOP_SALES_FAILURE';
export const TOP_SALES_SUCCESS = 'TOP_SALES_SUCCESS';

export const CATEGORIES_REQUEST = 'CATEGORIES_REQUEST';
export const CATEGORIES_FAILURE = 'CATEGORIES_FAILURE';
export const CATEGORIES_SUCCESS = 'CATEGORIES_SUCCESS';

export const ITEM_REQUEST = 'ITEM_REQUEST';
export const ITEM_FAILURE = 'ITEM_FAILURE';
export const ITEM_SUCCESS = 'ITEM_SUCCESS';

export const CATALOG_REQUEST = 'CATALOG_REQUEST';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS';
export const CATALOG_FILTER = 'CATALOG_FILTER';
export const CATALOG_MORE = 'CATALOG_MORE';

export const CART_ADD = 'CART_ADD';
export const CART_REMOVE = 'CART_REMOVE';
export const CART_GET = 'CART_GET';